### ISSUE TITLE
Feature request: animation for data insert?

### ISSUE THREAD

**Issue by kayazinc** [v1ack/svelte-virtual-scroll-list#4]
Use-case: to highlight (and fade off) whenever new row of data is inserted into the list.

I saw one of the examples is to insert 10 row on top, is it possible to show animation on the data inserted?

Thanks.

**Comment by v1ack** [comment]
Looks like it's possible.
You can make a transition function on top of svelte fade, in which you can determine if current call for new inserted data or for rerendered. Call svelte fade for first case and none for second
