### ISSUE TITLE
Feature request: Item row clicked event

### ISSUE THREAD

**Issue by kayazinc** [v1ack/svelte-virtual-scroll-list#5]
May i request for a new feature: trigger an event when item row is clicked?

Thanks

**Comment by v1ack** [comment]
Can you explain?
If you are talking about event on item - you can do it yourself by adding `on:click` 

Something like 
```svelte
<VirtualScroll
    bind:this={list}
    data={items}
    key="uniqueKey"
    let:data
>
    <div on:click={myClickAction}/>
      {data.uniqueKey}
    </div>
</VirtualScroll>
```

**Comment by v1ack** [comment]
You can search for Svelte communities online if you are new in Svelte
As I know, there is an English official Discord channel and Russian Telegram chat
